[package]
name = "MPK"
version = "0.0.0"

[addresses]
Std = "0x1"
AptosFramework = "0x1"
MPK = "0xDB0F23D1D3DE343795272F8E165AE7E425A9CC4761A0D660BED91FAA85CD5613"

[dependencies]
MoveStdlib = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "main" }
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
